package biz.golek.whattodofordinner.database.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DINNER_INGREDIENT".
 */
public class DinnerIngredient {

    private Long id;
    private long dinnerId;
    private long ingredientId;

    public DinnerIngredient() {
    }

    public DinnerIngredient(Long id) {
        this.id = id;
    }

    public DinnerIngredient(Long id, long dinnerId, long ingredientId) {
        this.id = id;
        this.dinnerId = dinnerId;
        this.ingredientId = ingredientId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getDinnerId() {
        return dinnerId;
    }

    public void setDinnerId(long dinnerId) {
        this.dinnerId = dinnerId;
    }

    public long getIngredientId() {
        return ingredientId;
    }

    public void setIngredientId(long ingredientId) {
        this.ingredientId = ingredientId;
    }

}
