package biz.golek.whattodofordinner.database;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import biz.golek.whattodofordinner.database.entities.DinnerIngredient;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DINNER_INGREDIENT".
*/
public class DinnerIngredientDao extends AbstractDao<DinnerIngredient, Long> {

    public static final String TABLENAME = "DINNER_INGREDIENT";

    /**
     * Properties of entity DinnerIngredient.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DinnerId = new Property(1, long.class, "dinnerId", false, "DINNER_ID");
        public final static Property IngredientId = new Property(2, long.class, "ingredientId", false, "INGREDIENT_ID");
    };

    private Query<DinnerIngredient> dinner_DinnerIngredientToDinnersQuery;
    private Query<DinnerIngredient> ingredient_DinnerIngredientToIngredientsQuery;

    public DinnerIngredientDao(DaoConfig config) {
        super(config);
    }
    
    public DinnerIngredientDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DINNER_INGREDIENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DINNER_ID\" INTEGER NOT NULL ," + // 1: dinnerId
                "\"INGREDIENT_ID\" INTEGER NOT NULL );"); // 2: ingredientId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DINNER_INGREDIENT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DinnerIngredient entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDinnerId());
        stmt.bindLong(3, entity.getIngredientId());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DinnerIngredient readEntity(Cursor cursor, int offset) {
        DinnerIngredient entity = new DinnerIngredient( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // dinnerId
            cursor.getLong(offset + 2) // ingredientId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DinnerIngredient entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDinnerId(cursor.getLong(offset + 1));
        entity.setIngredientId(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DinnerIngredient entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DinnerIngredient entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "DinnerIngredientToDinners" to-many relationship of Dinner. */
    public List<DinnerIngredient> _queryDinner_DinnerIngredientToDinners(long dinnerId) {
        synchronized (this) {
            if (dinner_DinnerIngredientToDinnersQuery == null) {
                QueryBuilder<DinnerIngredient> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.DinnerId.eq(null));
                dinner_DinnerIngredientToDinnersQuery = queryBuilder.build();
            }
        }
        Query<DinnerIngredient> query = dinner_DinnerIngredientToDinnersQuery.forCurrentThread();
        query.setParameter(0, dinnerId);
        return query.list();
    }

    /** Internal query to resolve the "DinnerIngredientToIngredients" to-many relationship of Ingredient. */
    public List<DinnerIngredient> _queryIngredient_DinnerIngredientToIngredients(long ingredientId) {
        synchronized (this) {
            if (ingredient_DinnerIngredientToIngredientsQuery == null) {
                QueryBuilder<DinnerIngredient> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IngredientId.eq(null));
                ingredient_DinnerIngredientToIngredientsQuery = queryBuilder.build();
            }
        }
        Query<DinnerIngredient> query = ingredient_DinnerIngredientToIngredientsQuery.forCurrentThread();
        query.setParameter(0, ingredientId);
        return query.list();
    }

}
