package biz.golek.whattodofordinner.business.contract.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DINNER_STAT".
 */
public class DinnerStat {

    private Long id;
    private int type;
    /** Not-null value. */
    private java.util.Date date;
    private long dinnerId;

    public DinnerStat() {
    }

    public DinnerStat(Long id) {
        this.id = id;
    }

    public DinnerStat(Long id, int type, java.util.Date date, long dinnerId) {
        this.id = id;
        this.type = type;
        this.date = date;
        this.dinnerId = dinnerId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public long getDinnerId() {
        return dinnerId;
    }

    public void setDinnerId(long dinnerId) {
        this.dinnerId = dinnerId;
    }

}
