package biz.golek.whattodofordinner.business.contract.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DINNER".
 */
public class Dinner {

    private Long id;
    /** Not-null value. */
    private String name;
    private int duration;
    private int seasons;
    private boolean soup;
    private boolean vegetarian;
    private java.util.Date lastUsage;
    private java.util.Date lastDrop;
    /** Not-null value. */
    private java.util.Date creationDate;

    public Dinner() {
    }

    public Dinner(Long id) {
        this.id = id;
    }

    public Dinner(Long id, String name, int duration, int seasons, boolean soup, boolean vegetarian, java.util.Date lastUsage, java.util.Date lastDrop, java.util.Date creationDate) {
        this.id = id;
        this.name = name;
        this.duration = duration;
        this.seasons = seasons;
        this.soup = soup;
        this.vegetarian = vegetarian;
        this.lastUsage = lastUsage;
        this.lastDrop = lastDrop;
        this.creationDate = creationDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getDuration() {
        return duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

    public int getSeasons() {
        return seasons;
    }

    public void setSeasons(int seasons) {
        this.seasons = seasons;
    }

    public boolean getSoup() {
        return soup;
    }

    public void setSoup(boolean soup) {
        this.soup = soup;
    }

    public boolean getVegetarian() {
        return vegetarian;
    }

    public void setVegetarian(boolean vegetarian) {
        this.vegetarian = vegetarian;
    }

    public java.util.Date getLastUsage() {
        return lastUsage;
    }

    public void setLastUsage(java.util.Date lastUsage) {
        this.lastUsage = lastUsage;
    }

    public java.util.Date getLastDrop() {
        return lastDrop;
    }

    public void setLastDrop(java.util.Date lastDrop) {
        this.lastDrop = lastDrop;
    }

    /** Not-null value. */
    public java.util.Date getCreationDate() {
        return creationDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreationDate(java.util.Date creationDate) {
        this.creationDate = creationDate;
    }

}
