package biz.golek.whattodofordinner.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DINNER".
 */
public class Dinner {

    private Long id;
    /** Not-null value. */
    private String name;
    private Integer duration;
    private Boolean soup;
    private Boolean vegetarian;

    public Dinner() {
    }

    public Dinner(Long id) {
        this.id = id;
    }

    public Dinner(Long id, String name, Integer duration, Boolean soup, Boolean vegetarian) {
        this.id = id;
        this.name = name;
        this.duration = duration;
        this.soup = soup;
        this.vegetarian = vegetarian;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public Boolean getSoup() {
        return soup;
    }

    public void setSoup(Boolean soup) {
        this.soup = soup;
    }

    public Boolean getVegetarian() {
        return vegetarian;
    }

    public void setVegetarian(Boolean vegetarian) {
        this.vegetarian = vegetarian;
    }

}
